version: '3.4'

services:
  sampleblogapp:
    image: msuddaby/sampleblogapp:latest
    environment:
        - ASPNETCORE_URLS=http://+:80
    ports:
        - "5600:80"
    expose:
        - "5600"
    build:
      context: .
      dockerfile: SampleBlogApp/Dockerfile
    secrets:
        - db-password

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    volumes:
        - dbdata:/var/opt/mssql
    env_file:
        - db/sqlserver.env
        - db/sapass.env

volumes:
  dbdata:

secrets:
    db-password:
        file: db/sapass.env