version: '3.4'

services:
  sampleblogapp:
    image: ${DOCKER_REGISTRY-}sampleblogapp
    build:
      context: .
      dockerfile: SampleBlogApp/Dockerfile
    secrets:
        - db-password

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    env_file:
        - db/sqlserver.env
        - db/sapass.env
  
secrets:
    db-password:
        file: db/sapass.env